update

diff --git a/win10 b/win10
--- a/win10
+++ b/win10
@@ -1,69 +1,53 @@
-#!/bin/bash
-set -e
+#!/usr/bin/env bash
+set -o errexit
+set -o pipefail
+set -o nounset
+
+info() {
+    echo "[info]" "$@"
+}
+
+err() {
+    echo "[error]" "$@" 2>&1
+}
+
+die() {
+    local code="$1"
+    shift
+
+    err "$@"
+    exit "${code}"
+}
 
 __func_defered=()
-defer() {
-    __func_defered+=("$*")
-}
 do_defer() {
     for ((i=${#__func_defered[@]}-1;i>=0;i--)); do
         if ! eval "${__func_defered[i]}"; then
-            echo "eval cmd failed, cmd: \"${__func_defered[i]}\"" >&2
+            die 1 "eval cmd failed, cmd: \"${__func_defered[i]}\""
         fi
     done
 }
 trap do_defer EXIT
+defer() {
+    __func_defered+=("$*")
+}
 
-main() {
-    if [ $UID != 0 ]; then
-        exec sudo "$0" "$@"
-    fi
-    if [ $PPID != 1 ]; then
-        # install: yay -S --noconfirm daemonize
-        mkdir -p log
-        exec daemonize -c "$PWD" -v -o log/out.log -e log/err.log "$(realpath $0)" "$@"
-    fi
+opt_edk2="/usr/share/edk2-ovmf/x64/OVMF_CODE.4m.fd"
+opt_rom="./assets/Gigabyte.RTX3090.24576.210315_3.rom"
 
-    if systemctl is-active --quiet display-manager.service; then
-        systemctl stop display-manager.service
-        while systemctl is-active --quiet display-manager.service; do
-            sleep 1
-        done
-        defer "systemctl start display-manager.service"
-    fi
+opts_qemu=(
+    "-nodefaults"
+    "-vga" "none"
+    "-nographic"
 
-    local qemu_options=()
-    qemu_options+=("-nodefaults" "-nographic" "-vga" "none")
+    "-machine" "q35,accel=kvm"
+    "-cpu" "host"
+    "-smp" "cores=32"
+    "-m" "48G"
+)
 
-    qemu_options+=("-enable-kvm")
-    qemu_options+=("-cpu" "host,kvm=off")
-    qemu_options+=("-smp" "cores=32")
-    qemu_options+=("-m" "32G")
-    qemu_options+=("-drive" "if=pflash,format=raw,readonly=on,file=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd")
-
-    # gpu passthrough
-    virsh nodedev-detach pci_0000_01_00_0
-    defer "virsh nodedev-reattach pci_0000_01_00_0"
-    virsh nodedev-detach pci_0000_01_00_1
-    defer "virsh nodedev-reattach pci_0000_01_00_1"
-    qemu_options+=(
-        "-device" "vfio-pci,host=01:00.0,x-vga=on,multifunction=on,romfile=${PWD}/assets/Gigabyte.RTX3090.24576.210315_3.rom"
-        "-device" "vfio-pci,host=01:00.1"
-    )
-
-    # usb controller passthrough
-    virsh nodedev-detach pci_0000_69_00_0
-    defer "virsh nodedev-reattach pci_0000_69_00_0"
-    qemu_options+=("-device" "vfio-pci,host=69:00.0")
-
-    # nic
-    qemu_options+=("-nic" "user")
-
-    systemd-inhibit --what=sleep --mode=block sleep infinity &
-    defer "kill $!"
-
-    # anti detection
-    qemu_options+=(
+do_anti_detection() {
+    opts_qemu+=(
         "-machine" "pc-q35-7.1,accel=kvm,usb=off,vmport=off,kernel_irqchip=on,dump-guest-core=off,hpet=off,acpi=on"
         "-cpu" "host,migratable=on,topoext=on,hypervisor=off,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff,hv-vendor-id=123456789ab,kvm=off,kvm-hint-dedicated=on"
 
@@ -80,14 +64,55 @@ main() {
 
         "-sandbox" "on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny"
     )
+}
 
-    qemu-system-x86_64 "${qemu_options[@]}" "$@"
+do_nic_setup() {
+    opts_qemu+=("-nic" "user")
+}
+
+do_gpu_passthrough() {
+    virsh nodedev-detach pci_0000_01_00_0
+    defer "virsh nodedev-reattach pci_0000_01_00_0"
+    virsh nodedev-detach pci_0000_01_00_1
+    defer "virsh nodedev-reattach pci_0000_01_00_1"
+
+    opts_qemu+=(
+        "-device" "vfio-pci,host=01:00.0,x-vga=on,multifunction=on,romfile=${opt_rom}"
+        "-device" "vfio-pci,host=01:00.1"
+    )
+}
+
+do_usb_passthrough() {
+    virsh nodedev-detach pci_0000_69_00_0
+    defer "virsh nodedev-reattach pci_0000_69_00_0"
+
+    opts_qemu+=(
+        "-device" "vfio-pci,host=69:00.0"
+    )
+}
+
+main() {
+    [ -n "${opt_edk2}" ] \
+        && opts_qemu+=("-drive" "if=pflash,format=raw,readonly=on,file=${opt_edk2}")
+
+    do_anti_detection
+    do_nic_setup
+    do_gpu_passthrough
+    do_usb_passthrough
+
+    if systemctl is-active --quiet display-manager.service; then
+        systemctl stop display-manager.service
+        while systemctl is-active --quiet display-manager.service; do
+            sleep 1
+        done
+        defer "systemctl start display-manager.service"
+    fi
+
+    systemd-inhibit --what=sleep --mode=block sleep infinity &
+    defer "kill $!"
+
+    qemu-system-x86_64 "${opts_qemu[@]}" "$@"
 }
 
 main "$@"
 
-# # disk
-# qemu_args+=(
-#     "-drive" "file=$(losetup -o 1GiB -f --show /dev/nvme1n1),if=virtio,media=disk,cache=unsafe,format=raw"
-#     "-drive" "file=/dev/loop0,if=virtio,media=disk,cache=unsafe,format=raw"
-# )
